#!/bin/bash
#==============================================================
# Scipt to setup up machine to use the post processing files 
# from any directory
# This script must be run from the scripts/ directory
#==============================================================

#Checking directory is correct
if [ ! -d bin ]; then
	cd ../
fi
if [ ! -d bin ]; then
	echo -e "This script must be run from either the \
main directory or the scripts directory...exiting\n"
	exit 1
fi
echo -e "\n *** SETTING UP CHAPSim_post ***\n"
echo -e "Making CHAPSim_post\n"

current_dir=$(pwd)
if [ ! -d core ]; then
	echo -e "This has not be initiated from the correct directory\n"
	exit 1
fi

#Modifying PYTHONPATH in .bashrc
#Ensuring that the .bashrc file isn't modified multiple times
if [ -f $HOME/.bashrc ]; then 
	if [ ! $(cat $HOME/.bashrc | grep PYTHONPATH=\"\$PYTHONPATH:\$CHAPSim_bin\") &>/dev/null ]; then
		current_dir=${current_dir// /"\ "}
		#Adding to .bashrc
		bashrc_mod="if [ -d \"$current_dir\" ]; then \n\tCHAPSim_bin=\"$current_dir/core\" \n\texport PYTHONPATH=\"\$PYTHONPATH:\$CHAPSim_bin\" \nfi"

		echo -e "\nModifying $HOME/.bashrc\n"
		echo -e "\n# *** CHAPSim_post setup ***" >> $HOME/.bashrc
		echo -e $bashrc_mod >> $HOME/.bashrc
	fi
fi

#Adding path to conda if present
if hash conda &>/dev/null ; then
	#Creating conda environment if not already present
	if [ ! $(conda env list | grep CHAPSim_post ) &>/dev/null ]; then
		#Create conda environment
		echo -e "### Creating conda environment\n"
		conda  env create -f scripts/CHAPSim_post.yml

		source activate CHAPSim_post
		#adds bin to conda's search path
		conda develop $current_dir/core
		wait
		#testing by importing module
		echo -e "### Testing conda environment\n "
	fi
	
	if $CONDA_PREFIX/bin/python -c "import CHAPSim_post.CHAPSim_post; import CHAPSim_post.CHAPSim_Tools; import CHAPSim_post.CHAPSim_plot; import CHAPSim_post.CHAPSim_dtypes" ; then
		echo -e "Import test complete" 
		conda deactivate
	else
		#If it fails it removes the created environment
		echo -e "Import test failed"
		conda deactivate
		conda remove --name CHAPSim_post -y --all
		exit 1
	fi

		

fi

echo -e "### Finished Setup of CHAPSim_post"


