#!/bin/bash
#==============================================================
# Scipt to setup up machine to use the post processing files 
# from any directory
#==============================================================

cd ../
echo -e "\n *** SETTING UP CHAPSim_post ***\n"
echo -e "Making CHAPSim_post\n"
make all
current_dir=$(pwd)

#Ensuring that the .bashrc file isn't modified multiple time

input=scripts/test.sh #$HOME/.bashrc
if [ -f $input ]; then 
	while IFS= read -r line
	do
		if [ "$line" == "if [ -d \"$current_dir\" ]; then " ]; then
			echo -e "\n$input already modified no changes required\n"
			exit 0
		fi
	done <"$input"
fi
current_dir=${current_dir// /"\ "}

#Adding to .bashrc
bashrc_mod="if [ -d \"$current_dir\" ]; then \n\tCHAPSim_bin=\"$current_dir/bin\" \n\tPYTHONPATH=\"\$PYTHONPATH:\$CHAPSim_bin\" \nfi"

echo -e "\nModifying $input\n"
echo -e "\n# *** CHAPSim_post setup ***" >> $input 
echo -e $bashrc_mod >> $input 

#Adding path to conda if present
if hash conda &>/dev/null ; then
	#Optional use of command line argument to give environment name, defaults to base 
	if [ $# -gt 0 ]; then
		source activate $1
	else
		source activate base
	fi
	conda develop $current_dir/bin
fi


